# Generated by Django 5.0.6 on 2024-08-01 08:22

from django.db import migrations


def create_test_project(apps, schema_editor):
    Project = apps.get_model('tracker', 'Project')
    Project.objects.create(name='Тестовый проект', start_date='2024-01-01', description='Описание тестового проекта')


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_issue_project'),
    ]

    operations = [
        migrations.RunPython(create_test_project),
    ]
